docs: fill doc string of `SubscriptionCallbackValue` and `SubscriptionCallbackStructValue`
rokamu623/CARET_analyze pull request #13
Opened 2023-12-15 07:19 UTC by rokamu623

## Description

## Related links

## Notes for reviewers

## Pre-review checklist for the PR author

- [ ] I've confirmed the [contribution guidelines](https://github.com/tier4/caret/blob/main/.github/CONTRIBUTING.md).
- [ ] The PR is ready for review.

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] (Optional) The PR has been properly tested with CARET_report verification.
- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

2023-12-20 02:02 UTC, emori-ctc requested changes

2023-12-20 02:02 UTC, emori-ctc commented on src/caret_analyze/value_objects/callback.py
> +
Delete the line break on line 382.

2023-12-21 01:51 UTC, rokamu623 commented on src/caret_analyze/value_objects/callback.py
> +
Fixed it in [fdd8c80](https://github.com/rokamu623/CARET_analyze/pull/13/commits/fdd8c80bec4ef0f21bbed1966c2434002fa07553).

2023-12-21 06:48 UTC, emori-ctc approved these changes
LGTM!

2023-12-21 07:00 UTC, merged